import type { ServiceDefinitionSeed } from '@stubrix/shared';
import {
  WIREMOCK_CONFIG_SCHEMA,
  WIREMOCK_RECORD_CONFIG_SCHEMA,
  MOCKOON_CONFIG_SCHEMA,
  MOCKOON_PROXY_CONFIG_SCHEMA,
  POSTGRES_CONFIG_SCHEMA,
  MYSQL_CONFIG_SCHEMA,
  ADMINER_CONFIG_SCHEMA,
  CLOUDBEAVER_CONFIG_SCHEMA,
  LOCALSTACK_CONFIG_SCHEMA,
  MINIO_CONFIG_SCHEMA,
  KEYCLOAK_CONFIG_SCHEMA,
  ZITADEL_CONFIG_SCHEMA,
  PROMETHEUS_CONFIG_SCHEMA,
  GRAFANA_CONFIG_SCHEMA,
  JAEGER_CONFIG_SCHEMA,
  REDPANDA_CONFIG_SCHEMA,
  RABBITMQ_CONFIG_SCHEMA,
  GRIPMOCK_CONFIG_SCHEMA,
  PACT_CONFIG_SCHEMA,
  TOXIPROXY_CONFIG_SCHEMA,
  CHROMADB_CONFIG_SCHEMA,
  OPENRAG_CONFIG_SCHEMA,
  HOPPSCOTCH_CONFIG_SCHEMA,
} from './service-schemas';

export const SERVICE_DEFINITIONS: ServiceDefinitionSeed[] = [
  // ─── Mock Engines ────────────────────────────────────────────
  {
    id: 'wiremock',
    name: 'WireMock',
    category: 'mock-engines',
    dockerProfile: 'wiremock',
    dockerService: 'wiremock',
    defaultPort: 8081,
    dependsOn: [],
    configSchema: WIREMOCK_CONFIG_SCHEMA,
  },
  {
    id: 'wiremock-record',
    name: 'WireMock Record',
    category: 'mock-engines',
    dockerProfile: 'wiremock-record',
    dockerService: 'wiremock-record',
    defaultPort: 8081,
    dependsOn: [],
    configSchema: WIREMOCK_RECORD_CONFIG_SCHEMA,
  },
  {
    id: 'mockoon',
    name: 'Mockoon',
    category: 'mock-engines',
    dockerProfile: 'mockoon',
    dockerService: 'mockoon',
    defaultPort: 8081,
    dependsOn: [],
    configSchema: MOCKOON_CONFIG_SCHEMA,
  },
  {
    id: 'mockoon-proxy',
    name: 'Mockoon Proxy',
    category: 'mock-engines',
    dockerProfile: 'mockoon-proxy',
    dockerService: 'mockoon-proxy',
    defaultPort: 8081,
    dependsOn: [],
    configSchema: MOCKOON_PROXY_CONFIG_SCHEMA,
  },
  // ─── Databases ───────────────────────────────────────────────
  {
    id: 'postgres',
    name: 'PostgreSQL 17',
    category: 'databases',
    dockerProfile: 'postgres',
    dockerService: 'db-postgres',
    defaultPort: 5442,
    dependsOn: [],
    configSchema: POSTGRES_CONFIG_SCHEMA,
  },
  {
    id: 'mysql',
    name: 'MySQL 8',
    category: 'databases',
    dockerProfile: 'mysql',
    dockerService: 'db-mysql',
    defaultPort: 3307,
    dependsOn: [],
    configSchema: MYSQL_CONFIG_SCHEMA,
  },
  // ─── DB Viewers ──────────────────────────────────────────────
  {
    id: 'adminer',
    name: 'Adminer',
    category: 'db-viewers',
    dockerProfile: 'adminer',
    dockerService: 'adminer',
    defaultPort: 8084,
    externalUrl: 'http://localhost:8084',
    dependsOn: ['postgres'],
    configSchema: ADMINER_CONFIG_SCHEMA,
  },
  {
    id: 'cloudbeaver',
    name: 'CloudBeaver',
    category: 'db-viewers',
    dockerProfile: 'cloudbeaver',
    dockerService: 'cloudbeaver',
    defaultPort: 8083,
    externalUrl: 'http://localhost:8083',
    dependsOn: [],
    configSchema: CLOUDBEAVER_CONFIG_SCHEMA,
  },
  // ─── Cloud ───────────────────────────────────────────────────
  {
    id: 'localstack',
    name: 'LocalStack (AWS)',
    category: 'cloud',
    dockerProfile: 'localstack',
    dockerService: 'localstack',
    defaultPort: 4566,
    externalUrl: 'http://localhost:4566',
    dependsOn: [],
    configSchema: LOCALSTACK_CONFIG_SCHEMA,
  },
  // ─── Storage ─────────────────────────────────────────────────
  {
    id: 'minio',
    name: 'MinIO (S3)',
    category: 'storage',
    dockerProfile: 'minio',
    dockerService: 'minio',
    defaultPort: 9000,
    externalUrl: 'http://localhost:9001',
    dependsOn: [],
    configSchema: MINIO_CONFIG_SCHEMA,
  },
  // ─── IAM ─────────────────────────────────────────────────────
  {
    id: 'keycloak',
    name: 'Keycloak',
    category: 'iam',
    dockerProfile: 'keycloak',
    dockerService: 'keycloak',
    defaultPort: 8180,
    externalUrl: 'http://localhost:8180',
    dependsOn: [],
    configSchema: KEYCLOAK_CONFIG_SCHEMA,
  },
  {
    id: 'zitadel',
    name: 'Zitadel',
    category: 'iam',
    dockerProfile: 'zitadel',
    dockerService: 'zitadel',
    defaultPort: 8085,
    externalUrl: 'http://localhost:8085',
    dependsOn: ['postgres'],
    configSchema: ZITADEL_CONFIG_SCHEMA,
  },
  // ─── Observability ───────────────────────────────────────────
  {
    id: 'prometheus',
    name: 'Prometheus',
    category: 'observability',
    dockerProfile: 'prometheus',
    dockerService: 'prometheus',
    defaultPort: 9091,
    externalUrl: 'http://localhost:9091',
    dependsOn: [],
    configSchema: PROMETHEUS_CONFIG_SCHEMA,
  },
  {
    id: 'grafana',
    name: 'Grafana',
    category: 'observability',
    dockerProfile: 'grafana',
    dockerService: 'grafana',
    defaultPort: 3000,
    externalUrl: 'http://localhost:3000',
    dependsOn: ['prometheus'],
    configSchema: GRAFANA_CONFIG_SCHEMA,
  },
  // ─── Tracing ─────────────────────────────────────────────────
  {
    id: 'jaeger',
    name: 'Jaeger',
    category: 'tracing',
    dockerProfile: 'jaeger',
    dockerService: 'jaeger',
    defaultPort: 16686,
    externalUrl: 'http://localhost:16686',
    dependsOn: [],
    configSchema: JAEGER_CONFIG_SCHEMA,
  },
  // ─── Events ──────────────────────────────────────────────────
  {
    id: 'redpanda',
    name: 'Redpanda (Kafka)',
    category: 'events',
    dockerProfile: 'kafka',
    dockerService: 'redpanda',
    defaultPort: 9092,
    dependsOn: [],
    configSchema: REDPANDA_CONFIG_SCHEMA,
  },
  {
    id: 'redpanda-console',
    name: 'Redpanda Console',
    category: 'events',
    dockerProfile: 'kafka',
    dockerService: 'redpanda-console',
    defaultPort: 8080,
    externalUrl: 'http://localhost:8080',
    dependsOn: ['redpanda'],
    configSchema: [],
  },
  {
    id: 'rabbitmq',
    name: 'RabbitMQ',
    category: 'events',
    dockerProfile: 'rabbitmq',
    dockerService: 'rabbitmq',
    defaultPort: 5672,
    externalUrl: 'http://localhost:15672',
    dependsOn: [],
    configSchema: RABBITMQ_CONFIG_SCHEMA,
  },
  // ─── Protocols ───────────────────────────────────────────────
  {
    id: 'gripmock',
    name: 'GripMock (gRPC)',
    category: 'protocols',
    dockerProfile: 'gripmock',
    dockerService: 'gripmock',
    defaultPort: 4770,
    dependsOn: [],
    configSchema: GRIPMOCK_CONFIG_SCHEMA,
  },
  // ─── Contracts ───────────────────────────────────────────────
  {
    id: 'pact-broker',
    name: 'Pact Broker',
    category: 'contracts',
    dockerProfile: 'pact',
    dockerService: 'pact-broker',
    defaultPort: 9292,
    externalUrl: 'http://localhost:9292',
    dependsOn: ['postgres'],
    configSchema: PACT_CONFIG_SCHEMA,
  },
  // ─── Chaos ───────────────────────────────────────────────────
  {
    id: 'toxiproxy',
    name: 'Toxiproxy',
    category: 'chaos',
    dockerProfile: 'toxiproxy',
    dockerService: 'toxiproxy',
    defaultPort: 8474,
    dependsOn: [],
    configSchema: TOXIPROXY_CONFIG_SCHEMA,
  },
  // ─── AI ──────────────────────────────────────────────────────
  {
    id: 'chromadb',
    name: 'ChromaDB',
    category: 'ai',
    dockerProfile: 'ai',
    dockerService: 'chromadb',
    defaultPort: 8000,
    dependsOn: [],
    configSchema: CHROMADB_CONFIG_SCHEMA,
  },
  {
    id: 'openrag',
    name: 'OpenRAG',
    category: 'ai',
    dockerProfile: 'ai',
    dockerService: 'openrag',
    dockerCompanions: ['openrag-langflow', 'openrag-opensearch'],
    defaultPort: 8888,
    externalUrl: 'http://localhost:8888',
    dependsOn: [],
    configSchema: OPENRAG_CONFIG_SCHEMA,
  },
  // ─── API Clients ─────────────────────────────────────────────
  {
    id: 'hoppscotch',
    name: 'Hoppscotch',
    category: 'api-clients',
    dockerProfile: 'hoppscotch',
    dockerService: 'hoppscotch',
    defaultPort: 3100,
    externalUrl: 'http://localhost:3100',
    dependsOn: ['postgres'],
    configSchema: HOPPSCOTCH_CONFIG_SCHEMA,
  },
];
